services:
  - type: web
    name: burger-house
    runtime: node
    plan: free
    buildCommand: echo ready
    startCommand: node server.js
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
   
